
/**
 * Return a globally unique identifier.
 *
 * Provide a way to generate a string guaranteed to be unique when compared
 * to other strings generated by this function.
 */

module.exports= function(){
  var d = new Date().getTime();
  var uuid = 'xxxxxxxxxxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
    var r = (d + Math.random()*16)%16 | 0;
    d = Math.floor(d/16);
    return (c=='x' ? r : (r&0x3|0x8)).toString(16);
  });
  //console.log("this is a guid %s",uuid);
  return uuid
};
